const languages = {
    2: 'Spanish', 
    3: 'French',
    4: 'German',
    5: 'Italian',
    6: 'Portuguese',
    7: 'Dutch',
    8: 'Russian',
    9: 'Chinese (Simplified)',
    10: 'Japanese',
    11: 'Korean',
    12: 'Arabic',
    13: 'Hindi',
    14: 'Turkish',
    15: 'Greek',
    16: 'Swedish',
    17: 'Norwegian',
    18: 'Danish',
    19: 'Finnish',
    20: 'Polish',
    21: 'Hungarian',
    22: 'Czech',
    23: 'Thai',
    24: 'Hebrew',
    25: 'Indonesian',
    26: 'Malay',
    27: 'Vietnamese',
    28: 'Romanian',
    29: 'Ukrainian',
    30: 'Bulgarian',
    31: 'Croatian',
    32: 'Serbian',
    33: 'Slovak',
    34: 'Slovenian',
    35: 'Lithuanian',
    36: 'Latvian',
    37: 'Estonian',
    38: 'Bengali',
    39: 'Tamil',
    40: 'Telugu',
    41: 'Urdu',
    42: 'Punjabi',
    43: 'Gujarati',
    44: 'Marathi',
    45: 'Kannada',
    46: 'Malayalam',
    47: 'Sinhala',
    48: 'Nepali',
    49: 'Swahili',
    50: 'Filipino'
};

module.exports = languages;
